### PR TITLE
Features discussed on 5/1/20: Annotations supporting neutral losses that are not formulae + SpectrumLibrary interface type

### PR DESCRIPTION
**Pull request by mobiusklein**
This PR implements several features discussed on the 5/1/20 call. 
1. Letting annotation neutral losses include `[Carbamidomethyl]` and `[57.245]` 
2. Fixing JSON backend to store analytes as Objects instead of Arrays.
3. Fixing Immonium ion symbol in annotation parser pattern

Also includes more work on the high level interface to the format type determination code wrapped inside `SpectrumLibrary`, and more unit tests.

Other internal renovations include starting code for reading text libraries from the start of the file to get ready to fulfill requests by sequential parsing when an index isn't present to eventually get rid of  the mandatory indexing in the first place. Also added logic to check if an SQL index exists and preferring that index when guessing which index type to use by default.

### CODE REVIEW

**Comment by mobiusklein** [comment]
@edeutsch were you able to find that example file with the header you mentioned at the end of the last meeting? Otherwise I was going to try something like
```
<mzSpecLib 1.0>
...
```
This will let me start exercising the attribute interface on the library level, and start looking at validation and header detection.

**Comment by edeutsch** [comment]
I just looked again everywhere and I do not find anything useful. So I suggest you just go ahead and mock up something that seems sensible and we'll discuss at the call. Ideally both a text form and a json form.
thanks!

**Comment by mobiusklein** [comment]
Text is straight-forward. If the format version is specified in the `<mzSpecLib (version)>` tag, should the attribute also be present? For now I'm assuming yes.

For JSON, I think we should simply have a top-level key-value-pair `format: "mzSpecLib"` rather than a separate header line which would not be valid JSON.

**Comment by edeutsch** [comment]
sure, for now what you propose seems good. We can tweak it after looking after some examples.

**Pull request merged**
